-- Catégories
insert into categories (id, name, sort_order) values
  ('petit-dejeuner', 'Petit Déjeuner', 0),
  ('resistance', 'Résistance', 1),
  ('grignotines', 'Les grignotines', 2),
  ('boissons', 'Nos boissons', 3),
  ('dessert', 'Dessert', 4)
on conflict (id) do nothing;

-- Sous-catégories
insert into subcategories (id, category_id, name, sort_order) values
  ('aperitif', 'boissons', 'Apéritif', 0),
  ('sobebra', 'boissons', 'Sobebra (bière)', 1),
  ('eau', 'boissons', 'Eau', 2),
  ('sucreries-canette', 'boissons', 'Sucreries en canette', 3),
  ('boissons-energisantes', 'boissons', 'Boissons énergisantes', 4),
  ('jus-naturel', 'boissons', 'Jus naturel', 5)
on conflict (id) do nothing;

-- Produits
insert into products (id, category_id, subcategory_id, name, description, prices, sort_order) values
  ('cafe-au-lait-chaud', 'petit-dejeuner', null, 'Café au lait chaud', '', array[250], 0),
  ('cafe-au-lait-froid', 'petit-dejeuner', null, 'Café au lait froid', '', array[300], 1),
  ('lait-peak-cafe-chaud', 'petit-dejeuner', null, 'Lait peak au café chaud', '', array[700], 2),
  ('lait-peak-cafe-froid', 'petit-dejeuner', null, 'Lait peak au café froid', '', array[800], 3),
  ('lipton', 'petit-dejeuner', null, 'Lipton', '', array[150], 4),
  ('omelette', 'petit-dejeuner', null, 'Omelette', '', array[500], 5),
  ('alloco-omelette', 'petit-dejeuner', null, 'Alloco + omelette', '', array[600], 6),
  ('indomie', 'petit-dejeuner', null, 'Indomie', 'Portion simple ou double.', array[500,800], 7),
  ('spaghettis', 'petit-dejeuner', null, 'Spaghettis', 'Petite, moyenne ou grande portion.', array[500,1000,1500], 8),
  ('coquillettes', 'petit-dejeuner', null, 'Coquillettes', 'Petite ou grande portion.', array[500,1000], 9),
  ('sandwich-viande-hachee', 'petit-dejeuner', null, 'Sandwich viande hachée', '', array[1500], 10),
  ('chawarma', 'petit-dejeuner', null, 'Chawarma', 'Petite, moyenne ou grande taille.', array[1000,1500,2000], 11),
  ('frite-au-poulet', 'petit-dejeuner', null, 'Frite au poulet', 'Petite ou grande portion.', array[1500,2000], 12),
  ('salade', 'petit-dejeuner', null, 'Salade', 'Petite, moyenne ou grande portion.', array[1200,1500,2000], 13),
  ('riz-gras-creole-frite-aloco', 'resistance', null, 'Riz gras/créole + frite/aloco', '', array[2000], 14),
  ('riz-blanc-sauce-gesier-poulet', 'resistance', null, 'Riz blanc + sauce gésier/poulet', 'Portion gésier ou poulet.', array[1500,2000], 15),
  ('couscous', 'resistance', null, 'Couscous', 'Petite, moyenne ou grande portion.', array[1000,1500,2000], 16),
  ('attieke', 'resistance', null, 'Attiéké', 'Petite, moyenne ou grande portion.', array[1000,1500,2000], 17),
  ('piron-rouge', 'resistance', null, 'Piron rouge', 'Petite ou grande portion.', array[1200,2000], 18),
  ('sauce-legume-blanc-pate', 'resistance', null, 'Sauce légume blanc (gboman/tchayo/amanvivê) + pâte au choix', '', array[3000], 19),
  ('sauce-gluante-crincrin-gombo-pate', 'resistance', null, 'Sauce gluante crincrin/gombo + pâte au choix', '', array[2500], 20),
  ('akassa-monyo-jus-oignons', 'resistance', null, 'Akassa + monyo/jus d’oignons', 'Petite ou grande portion.', array[1500,2000], 21),
  ('croissant', 'grignotines', null, 'Croissant', 'Petit ou grand format.', array[300,400], 22),
  ('cake', 'grignotines', null, 'Cake', 'Petite part ou cake entier.', array[100,500], 23),
  ('biscuits-au-choix', 'grignotines', null, 'Biscuits au choix', 'À partir de 100 f selon le choix.', array[100], 24),
  ('arachide', 'grignotines', null, 'Arachide', '', array[100], 25),
  ('aperitif-sodabi-amansidji', 'boissons', 'aperitif', 'Apéritif (sodabi, amansidji)', 'Petit ou grand format.', array[100,200], 26),
  ('beninoise', 'boissons', 'sobebra', 'Béninoise', 'Petit ou grand format.', array[350,600], 27),
  ('doppel', 'boissons', 'sobebra', 'Doppel', '', array[650], 28),
  ('beaufort', 'boissons', 'sobebra', 'Beaufort', '', array[600], 29),
  ('guiness', 'boissons', 'sobebra', 'Guiness', '', array[800], 30),
  ('flag', 'boissons', 'sobebra', 'Flag', '', array[700], 31),
  ('pils', 'boissons', 'sobebra', 'Pils', '', array[700], 32),
  ('eku', 'boissons', 'sobebra', 'Eku', '', array[600], 33),
  ('hagbe-panache', 'boissons', 'sobebra', 'Hagbê (Panache)', '', array[600], 34),
  ('chill', 'boissons', 'sobebra', 'Chill', 'Petit ou grand format.', array[350,600], 35),
  ('tequila', 'boissons', 'sobebra', 'Tequila', '', array[500], 36),
  ('youki-pamplemousse', 'boissons', 'sobebra', 'Youki pamplemousse', 'Petit ou grand format.', array[400,1000], 37),
  ('youki-cocktails', 'boissons', 'sobebra', 'Youki cocktails', 'Petit ou grand format.', array[400,1000], 38),
  ('youki-moka', 'boissons', 'sobebra', 'Youki moka', '', array[400], 39),
  ('contesse', 'boissons', 'eau', 'Contesse', '', array[600], 40),
  ('fifa', 'boissons', 'eau', 'FIFA', '', array[500], 41),
  ('possotome-gazeifie', 'boissons', 'eau', 'Possotome gazéifié', '', array[500], 42),
  ('coca', 'boissons', 'sucreries-canette', 'Coca', '', array[400], 43),
  ('fanta', 'boissons', 'sucreries-canette', 'Fanta', '', array[400], 44),
  ('sprite', 'boissons', 'sucreries-canette', 'Sprite', '', array[400], 45),
  ('malta-guiness', 'boissons', 'sucreries-canette', 'Malta guiness', '', array[500], 46),
  ('desperados', 'boissons', 'sucreries-canette', 'Desperados', '', array[500], 47),
  ('budweiser', 'boissons', 'sucreries-canette', 'Budweiser', '', array[500], 48),
  ('xxl', 'boissons', 'boissons-energisantes', 'XXL', '', array[600], 49),
  ('vody', 'boissons', 'boissons-energisantes', 'Vody', '', array[700], 50),
  ('sangria', 'boissons', 'boissons-energisantes', 'Sangria', '', array[400], 51),
  ('chateau-de-france', 'boissons', 'boissons-energisantes', 'Château de France', '', array[400], 52),
  ('jus-ananas', 'boissons', 'jus-naturel', 'Jus d’ananas', 'Petit ou grand format.', array[500,1000], 53),
  ('jus-bissap', 'boissons', 'jus-naturel', 'Jus de bissap', 'Petit ou grand format.', array[500,1000], 54),
  ('degue-sorgho-couscous', 'dessert', null, 'Dêguê sorgho/couscous', 'Petite ou grande portion.', array[300,500], 55),
  ('degue-arachide', 'dessert', null, 'Dêguê + arachide', '', array[700], 56),
  ('degue-coco-rape', 'dessert', null, 'Dêguê + coco rapé', '', array[700], 57),
  ('lait-caille', 'dessert', null, 'Lait caillé', '', array[500], 58),
  ('lait-caille-lait-concentre', 'dessert', null, 'Lait caillé + lait concentré', '', array[600], 59),
  ('yaourt-simple', 'dessert', null, 'Yaourt simple', '', array[500], 60),
  ('yaourt-menthe', 'dessert', null, 'Yaourt à la menthe', '', array[1000], 61),
  ('yaourt-coco', 'dessert', null, 'Yaourt coco', '', array[1000], 62),
  ('yaourt-chocolat', 'dessert', null, 'Yaourt au chocolat', '', array[1000], 63)
on conflict (id) do nothing;
